server:
  port: 8080
  error:
    path: /error
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

logging:
  level:
    root:
      INFO
    web:
      INFO
    org.springframework.web:
      INFO
    org.springframework.data:
      INFO

spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: jdbc:h2:mem:portfoliosdb
    username: sa
    password: password
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    default-property-inclusion: non_null

# FMP api key
fmp:
  api-key: define-your-own-key